[workspace]
members = [
    "crates/services/web-server",
    "crates/libs/lib-core",
    "crates/libs/lib-auth",
    "crates/libs/lib-rpc",
    "crates/libs/lib-utils",
]
resolver = "2"
default-members = ["crates/services/web-server"]