services:
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "127.0.0.1:3306:3306"
  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  mysql-data:
  redis-data: