### 用户名为空
POST http://{{api}}/login
Content-Type: application/json

{
  "username": "",
  "password": "里斯"
}

### 账号不存在
POST http://{{api}}/login
Content-Type: application/json

{
  "username": "test-2",
  "password": "里斯"
}

### 登录成功
POST http://{{api}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "里斯"
}

### 获取用户列表失败-不带cookie
#@no-cookie-jar
GET http://{{api}}/users

### 获取用户列表-不带cookie
#@no-cookie-jar
GET http://{{api}}/users
Cookie: session=123


### 此请求会让服务器下发cookie
#@name 登录
POST http://{{api}}/login
Content-Type: application/json

{
  "username": "zhangsan",
  "password": ""
}

### 获取用户列表 - 成功
GET http://{{api}}/users

### 创建用户
POST http://localhost:7000/users
Content-Type: application/json

{
  "username": "test2"
}

### 测试Cookie
#@no-cookie-jar
GET http://{{api}}/cookie/language
Cookie:

###
WEBSOCKET ws://{{api}}/ws

### 获取当前登录用户信息
GET http://{{api}}/users/self

### 退出登录
GET http://{{api}}/users/logout

### http-test
GET http://{{api}}/http/get