### 用户名为空
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "",
  "password": "里斯"
}

### 账号不存在
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "你好",
  "password": "里斯"
}

### 登录成功
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "你好",
  "password": "里斯"
}

### 获取用户列表失败-不带cookie
#@no-cookie-jar
GET http://localhost:3000/users

### 获取用户列表-不带cookie
#@no-cookie-jar
GET http://localhost:3000/users
Cookie: session=123


### 此请求会让服务器下发cookie
#@name 登录
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "zhangsan",
  "password": ""
}

### 获取用户列表 - 成功
GET http://localhost:3000/users

### 创建用户
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "test"
}

### 测试Cookie
#@no-cookie-jar
GET http://localhost:3000/cookie/language
Cookie:

###
WEBSOCKET ws://localhost:3000/ws

### 获取当前登录用户信息
GET http://localhost:3000/users/self

### 退出登录
GET http://localhost:3000/users/logout

### http-test
GET http://localhost:3000/http/get